name: Generate snake game

on:
  schedule: # ejecuta cada 12 horas
    - cron: "* */12 * * *"
  workflow_dispatch: # permite disparar el workflow manualmente

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Crear la animaci√≥n Snake
      - uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: Lic-AlexGomez
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'  # Puedes cambiar el color si deseas un color diferente

      # Publicar en GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
